version: "3.7"



services:
  exchange:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=in_debug_mode_we_dont_need_keys
      - AWS_SECRET_ACCESS_KEY=docker_throws_errors_if_its_not_set

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"